# ESPHome code to interface to a Velux dumb remote to control a window or skylight
substitutions:
  # Add the name of your device here
  friendly_name: "Skylight"
  name: skylight
  api_key: "add_your_api_encryption_key_here"

esphome:
  name: ${name}
  friendly_name: ${friendly_name}

# Define the ESP you are using below.  This example uses a standard ESP32 WROOM.
esp32:
  board: esp32dev
  variant: esp32
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
# If using encryption change key to your encryption key (or comment for no encryption)
api:
  encryption:
    key: "${api_key}"

# Add ota_password to secrets or hardcode it below if you want an OTA password, or comment out password for no ota password
ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  # Add hotspot_password to secrets or hardcode it below for the hotspot password
  ap:
    ssid: "${friendly_name} Fallback Hotspot"
    password: !secret hotspot_password

captive_portal:

#web_server:
#  port: 80
#  include_internal: true

# Below is if you also want this remote to be a bluetooth proxy and bluetooth tracker for Bermuda (default enabled, comment out this section if you do not want this)
esp32_ble_tracker:
  scan_parameters:
#    interval: 1100ms
#    window: 1100ms
    active: true

bluetooth_proxy:
  active: true

# Wire up three GPIO pins to the Velux remote as indicated below.  Stop is optional but included here.
# These switches are internal only and not exported to Home Assistant
switch:
  - platform: gpio
    pin:
      number: GPIO25
      inverted: true
      mode:
        output: true
        open_drain: true
    name: "Open Switch"
    id: open_switch
    internal: true
  - platform: gpio
    pin:
      number: GPIO27
      inverted: true
      mode:
        output: true
        open_drain: true
    name: "Close Switch"
    id: close_switch
    internal: true
  - platform: gpio
    pin:
      number: GPIO26
      inverted: true
      mode:
        output: true
        open_drain: true
    name: "Stop Switch"
    id: stop_switch
    internal: true
    
# Cover is exported to Home Assistant    
cover:
  - platform: template
    device_class: window
    name: "${friendly_name}"
    open_action:
      # Cancel any previous action
      - switch.turn_off: close_switch
      - switch.turn_off: stop_switch
      # Turn the OPEN switch on briefly
      - switch.turn_on: open_switch
      - delay: 0.2s
      - switch.turn_off: open_switch
    close_action:
      # Cancel any previous action
      - switch.turn_off: open_switch
      - switch.turn_off: stop_switch
      # Turn the CLOSE switch on briefly
      - switch.turn_on: close_switch
      - delay: 0.2s
      - switch.turn_off: close_switch
    stop_action:
      # Cancel any previous action
      - switch.turn_off: open_switch
      - switch.turn_off: close_switch
      # Turn the STOP switch on briefly
      - switch.turn_on: stop_switch
      - delay: 0.2s
      - switch.turn_off: stop_switch
    optimistic: true
    assumed_state: true
